"""Data loader with ticker extraction and explosion for the surge-labelling pipeline.

Loads the Reddit submissions CSV, extracts tickers from title/selftext using
regex patterns, handles missing/deleted text, and explodes multi-ticker records
into one row per (record_id, ticker) pair.

Requirements: R1 (Data Loading and Ticker Extraction)
"""

from __future__ import annotations

import hashlib
import logging
import random
import re
import string
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

from surge_pipeline.config import PipelineConfig

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Stopwords: common English words and Reddit/finance terms that look like
# tickers and must be rejected during extraction.
#
# The lexicon is generated by ``src/build_stopwords.py`` from two
# clearly-separated sources -- an English base drawn mechanically from the
# NLTK stopwords corpus, and a curated, categorised domain supplement -- and
# written to the package data file ``surge_pipeline/data/ticker_stopwords.txt``.
# This module simply loads that file, so the term list stays auditable,
# reproducible, and free of magic literals. Regenerate the data file whenever
# the recipe changes. Shipping the file inside the package means it travels
# with the installed wheel rather than depending on the source-tree layout.
# ---------------------------------------------------------------------------

#: Path to the generated stopword data file (resolved relative to this package).
STOPWORDS_PATH: Path = Path(__file__).resolve().parent / "data" / "ticker_stopwords.txt"


def _load_stopwords(path: Path = STOPWORDS_PATH) -> set[str]:
    """Load the stopword lexicon from the reference data file.

    The file is a plain-text list of upper-case terms, one per line; blank
    lines and ``#`` comment/section-header lines are ignored.

    Returns
    -------
    set[str]
        The stopword terms. Raises ``FileNotFoundError`` with a build hint if
        the data file is missing (e.g. after a checkout without running the
        build script).
    """
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"Stopword data file not found: {path}. "
            "Generate it with: python src/build_stopwords.py"
        ) from exc

    terms: set[str] = set()
    for line in text.splitlines():
        token = line.strip()
        if not token or token.startswith("#"):
            continue
        terms.add(token.upper())
    return terms


#: Stopword set used for ticker filtering, loaded from the reference data file.
TICKER_STOPWORDS: set[str] = _load_stopwords()

# Regex patterns for ticker extraction
_DOLLAR_SIGN_PATTERN = re.compile(r"\$([A-Z]{1,5})")
_UPPERCASE_WORD_PATTERN = re.compile(r"\b([A-Z]{2,5})\b")


# ---------------------------------------------------------------------------
# CSV reading helper (clear errors at the I/O boundary)
# ---------------------------------------------------------------------------


def _read_csv(
    file_path: Path,
    nrows: int | None = None,
    usecols: list[str] | None = None,
) -> pd.DataFrame:
    """Read a CSV, converting low-level pandas/OS errors into clear messages.

    Wraps :func:`pandas.read_csv` so that malformed, empty, or unreadable
    input surfaces as an actionable ``ValueError``/``FileNotFoundError`` that
    names the offending file, rather than an opaque pandas traceback.

    Parameters
    ----------
    file_path : Path
        Path to the CSV file.
    nrows : int, optional
        Maximum number of rows to read (forwarded to ``pandas.read_csv``).
    usecols : list[str], optional
        Subset of columns to read (forwarded to ``pandas.read_csv``).

    Returns
    -------
    pd.DataFrame

    Raises
    ------
    FileNotFoundError
        If the file does not exist at read time.
    ValueError
        If the file is empty, malformed, or not valid UTF-8 text.
    """
    try:
        return pd.read_csv(file_path, nrows=nrows, usecols=usecols)
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Input CSV not found: {file_path}") from exc
    except pd.errors.EmptyDataError as exc:
        raise ValueError(f"Input CSV is empty: {file_path}") from exc
    except pd.errors.ParserError as exc:
        raise ValueError(
            f"Input CSV is malformed and could not be parsed: {file_path} ({exc})"
        ) from exc
    except UnicodeDecodeError as exc:
        raise ValueError(
            f"Input CSV is not valid UTF-8 text: {file_path} ({exc})"
        ) from exc
    except OSError as exc:
        raise ValueError(f"Could not read input CSV: {file_path} ({exc})") from exc


# ---------------------------------------------------------------------------
# Ticker extraction
# ---------------------------------------------------------------------------


def extract_tickers(title: str, selftext: str) -> list[str]:
    """Extract stock tickers from post title and selftext.

    Strategy:
        1. Dollar-sign pattern (highest priority): $BNGO, $AMC, etc.
        2. Uppercase word pattern: standalone 2-5 char uppercase words.
        3. Filter against stopword set to exclude common English/Reddit terms.
        4. Deduplicate across title and selftext.

    Parameters
    ----------
    title : str
        The post title text.
    selftext : str
        The post body text.

    Returns
    -------
    List[str]
        Sorted list of unique extracted tickers (may be empty).
    """
    tickers: set[str] = set()

    # Defensive cast: guard against non-string values (e.g. floats/NaN from
    # mixed-type CSV columns) that would otherwise be scanned as "nan".
    combined_text = f"{title!s} {selftext!s}"

    # 1. Dollar-sign pattern (highest priority — always included)
    dollar_matches = _DOLLAR_SIGN_PATTERN.findall(combined_text)
    for match in dollar_matches:
        ticker = match.upper()
        if ticker not in TICKER_STOPWORDS:
            tickers.add(ticker)

    # 2. Uppercase word pattern (filtered against stopwords)
    word_matches = _UPPERCASE_WORD_PATTERN.findall(combined_text)
    for match in word_matches:
        ticker = match.upper()
        if ticker not in TICKER_STOPWORDS:
            tickers.add(ticker)

    return sorted(tickers)


# ---------------------------------------------------------------------------
# Sample tickers used by the synthetic data generator
# ---------------------------------------------------------------------------
_SAMPLE_TICKERS = [
    "AMC", "GME", "BBBY", "AAPL", "TSLA", "PLTR", "BB", "NOK",
    "WISH", "CLOV", "SOFI", "LCID", "RIVN", "MVIS", "SNDL",
    "TLRY", "DKNG", "NIO", "XPEV", "LI", "SPCE", "WKHS",
]


# ---------------------------------------------------------------------------
# Synthetic data generator (R1 development fallback)
# ---------------------------------------------------------------------------


def generate_synthetic_data(
    n_records: int = 500,
    seed: int = 42,
) -> pd.DataFrame:
    """Generate synthetic Reddit-style records mimicking the pennystocks schema.

    Used when the raw CSV is not available locally, enabling development
    and testing without the real dataset.

    Parameters
    ----------
    n_records : int
        Number of synthetic records to generate (default 500).
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    pd.DataFrame
        DataFrame matching the expected CSV schema.
    """
    if n_records < 0:
        raise ValueError(f"n_records must be non-negative, got {n_records}.")

    rng = random.Random(seed)
    np_rng = np.random.default_rng(seed)

    base_time = datetime(2021, 1, 1)
    records = []

    for i in range(n_records):
        record_id = "".join(rng.choices(string.ascii_lowercase + string.digits, k=7))

        # Timestamps spread over ~2 years, roughly sorted with some jitter
        offset_seconds = int(i * 3600 * 4 + rng.randint(-3600, 3600))
        created_utc = base_time + timedelta(seconds=offset_seconds)

        title = f"Synthetic post about stocks #{i}"
        selftext = f"Discussion body for record {record_id}." if rng.random() > 0.3 else ""

        score = int(np_rng.exponential(scale=50))
        num_comments = int(np_rng.exponential(scale=20))
        subreddit = rng.choice(["pennystocks", "wallstreetbets", "stocks"])

        # Ticker assignment: ~10% empty, ~50% single, ~40% multi
        roll = rng.random()
        if roll < 0.10:
            tickers = ""
        elif roll < 0.60:
            tickers = rng.choice(_SAMPLE_TICKERS)
        else:
            n_tickers = rng.randint(2, 4)
            tickers = ",".join(rng.sample(_SAMPLE_TICKERS, n_tickers))

        records.append(
            {
                "id": record_id,
                "created_utc": created_utc.timestamp(),
                "title": title,
                "selftext": selftext,
                "score": score,
                "num_comments": num_comments,
                "subreddit": subreddit,
                "tickers": tickers,
            }
        )

    df = pd.DataFrame(records)
    logger.info("Generated %d synthetic records for development.", n_records)
    return df


# ---------------------------------------------------------------------------
# Dataset fingerprinting for cross-machine reproducibility
# ---------------------------------------------------------------------------


def compute_dataset_fingerprint(file_path: Path) -> dict[str, object]:
    """Compute a reproducibility fingerprint for the raw CSV.

    Produces a SHA-256 hash of the file content plus structural metadata
    (row count, column names, timestamp range) so that two machines can
    verify they are working from identical source data.

    Parameters
    ----------
    file_path : Path
        Path to the raw CSV file.

    Returns
    -------
    dict
        Fingerprint dictionary with keys: sha256, file_size_bytes, columns,
        num_rows, timestamp_column, timestamp_min, timestamp_max,
        has_tickers_column.
    """
    # File-level hash (detects any byte-level difference)
    try:
        sha256 = hashlib.sha256(file_path.read_bytes()).hexdigest()
        file_size = file_path.stat().st_size
    except OSError as exc:
        raise ValueError(
            f"Could not read input CSV for fingerprinting: {file_path} ({exc})"
        ) from exc

    # Timestamp column detection uses the header only.
    df_head = _read_csv(file_path, nrows=5)
    columns = sorted(df_head.columns.tolist())

    # Logical row count: parse only the first column so embedded newlines in
    # quoted fields (common in Reddit selftext) are counted as one row each,
    # matching pandas' row semantics rather than raw file lines.
    if len(df_head.columns) > 0:
        first_col = df_head.columns[0]
        num_rows = len(_read_csv(file_path, usecols=[first_col]))
    else:
        num_rows = 0

    # Timestamp column detection
    ts_col = None
    ts_min = None
    ts_max = None
    if "created_utc" in df_head.columns:
        ts_col = "created_utc"
        # Read just the timestamp column for min/max
        ts_series = _read_csv(file_path, usecols=[ts_col])
        ts_min = float(ts_series[ts_col].min())
        ts_max = float(ts_series[ts_col].max())
    elif "created" in df_head.columns:
        ts_col = "created"
        ts_series = _read_csv(file_path, usecols=[ts_col])
        ts_min = str(ts_series[ts_col].min())
        ts_max = str(ts_series[ts_col].max())

    fingerprint = {
        "sha256": sha256,
        "file_size_bytes": file_size,
        "columns": columns,
        "num_rows": num_rows,
        "timestamp_column": ts_col,
        "timestamp_min": ts_min,
        "timestamp_max": ts_max,
        "has_tickers_column": "tickers" in columns,
    }

    logger.info(
        "Dataset fingerprint — SHA256: %.16s... | rows: %d | ts_col: %s | "
        "has_tickers: %s",
        sha256,
        num_rows,
        ts_col,
        "tickers" in columns,
    )

    return fingerprint


# ---------------------------------------------------------------------------
# Core loader
# ---------------------------------------------------------------------------


def load_data(config: PipelineConfig) -> pd.DataFrame:
    """Load and preprocess the Reddit submissions dataset.

    Workflow:
        1. Load from CSV (or generate synthetic data if file unavailable).
        2. Handle real dataset: extract tickers from title/selftext.
        3. Parse timestamps (epoch seconds or datetime strings) and sort (AC2).
        4. Exclude records with no identifiable ticker (AC4).
        5. Explode multi-ticker records into one row per (id, ticker) (AC3).
        6. Log record counts at each step (AC5).

    Parameters
    ----------
    config : PipelineConfig
        Pipeline configuration containing ``file_path`` and ``random_seed``.

    Returns
    -------
    pd.DataFrame
        Preprocessed DataFrame with one row per (record, ticker) pair,
        sorted chronologically.
    """
    # ------------------------------------------------------------------
    # Step 1: Load raw data (AC1)
    # ------------------------------------------------------------------
    file_path = Path(config.file_path) if config.file_path else None

    if file_path and file_path.exists():
        logger.info("Loading data from %s", file_path)
        df = _read_csv(file_path)
        if df.empty:
            raise ValueError(f"Input CSV contains no data rows: {file_path}")
        is_synthetic = False
        fingerprint = compute_dataset_fingerprint(file_path)
    else:
        if file_path:
            logger.warning(
                "File not found: %s — falling back to synthetic data.", file_path
            )
        else:
            logger.info("No file_path configured — using synthetic data.")
        df = generate_synthetic_data(n_records=500, seed=config.random_seed)
        is_synthetic = True
        fingerprint = {"sha256": "synthetic", "num_rows": len(df), "columns": sorted(df.columns.tolist())}

    total_loaded = len(df)
    logger.info("Records loaded: %d", total_loaded)

    # ------------------------------------------------------------------
    # Step 2: Handle ticker extraction for real data (no 'tickers' column)
    # ------------------------------------------------------------------
    if "tickers" not in df.columns and not is_synthetic:
        logger.info("No 'tickers' column found — extracting tickers from title/selftext.")

        missing_cols = [c for c in ("title", "selftext") if c not in df.columns]
        if missing_cols:
            raise ValueError(
                "Cannot extract tickers: input CSV is missing required column(s) "
                f"{missing_cols}. Expected 'title' and 'selftext', or a "
                "precomputed 'tickers' column."
            )

        # Clean selftext: replace [deleted], [removed], NaN with empty string
        df["selftext"] = df["selftext"].fillna("")
        df["selftext"] = df["selftext"].replace(
            {"[deleted]": "", "[removed]": ""}
        )

        # Clean title: fill NaN with empty string
        df["title"] = df["title"].fillna("")

        # Extract tickers per record. Iterating over the two columns directly
        # (rather than df.apply(axis=1)) avoids constructing a Series per row
        # and is substantially faster on large datasets (~1M+ rows).
        df["tickers"] = [
            ",".join(extract_tickers(title, selftext))
            for title, selftext in zip(
                df["title"].to_numpy(), df["selftext"].to_numpy()
            )
        ]

        # Log extraction statistics
        ticker_counts = df["tickers"].apply(
            lambda x: len(x.split(",")) if x else 0
        )
        avg_tickers = ticker_counts.mean()
        zero_ticker_pct = (ticker_counts == 0).sum() / len(df) * 100

        logger.info(
            "Ticker extraction stats — Avg tickers per record: %.2f | "
            "Records with 0 tickers: %.1f%%",
            avg_tickers,
            zero_ticker_pct,
        )

    # ------------------------------------------------------------------
    # Step 3: Parse timestamps and sort chronologically (AC2)
    # ------------------------------------------------------------------
    if "created_utc" in df.columns:
        # Synthetic data or datasets with epoch-second timestamps
        try:
            df["created_utc"] = pd.to_datetime(
                df["created_utc"], unit="s", utc=True, errors="coerce"
            )
        except (ValueError, TypeError) as exc:
            raise ValueError(
                f"Could not parse 'created_utc' as epoch seconds: {exc}"
            ) from exc
        ts_source = "created_utc"
    elif "created" in df.columns:
        # Real dataset with datetime string format (e.g., "2021-01-01 00:13:41")
        df["created_utc"] = pd.to_datetime(df["created"], utc=True, errors="coerce")
        df = df.drop(columns=["created"])
        ts_source = "created"
    else:
        raise ValueError(
            "Dataset must contain either 'created_utc' (epoch) or 'created' (datetime string) column."
        )

    # Fail loudly on unparseable timestamps rather than letting NaT values
    # silently corrupt the chronological ordering the whole pipeline depends on.
    n_invalid = int(df["created_utc"].isna().sum())
    if n_invalid > 0:
        raise ValueError(
            f"{n_invalid} record(s) have an unparseable '{ts_source}' timestamp. "
            "All timestamps must be valid to preserve chronological ordering."
        )

    df = df.sort_values("created_utc").reset_index(drop=True)
    logger.info("Timestamps parsed and sorted chronologically.")

    # ------------------------------------------------------------------
    # Step 4: Exclude records with missing/empty tickers (AC4)
    # ------------------------------------------------------------------
    # Convert to string, strip whitespace, replace empty strings with NaN
    df["tickers"] = df["tickers"].astype(str).str.strip()
    df["tickers"] = df["tickers"].replace({"": np.nan, "nan": np.nan, "None": np.nan})

    mask_has_tickers = df["tickers"].notna()
    excluded_count = (~mask_has_tickers).sum()
    df = df[mask_has_tickers].reset_index(drop=True)

    retained_before_explode = len(df)
    logger.info(
        "Records excluded (no tickers): %d | Retained: %d",
        excluded_count,
        retained_before_explode,
    )

    # ------------------------------------------------------------------
    # Step 5: Explode multi-ticker records (AC3)
    # ------------------------------------------------------------------
    # Split comma-separated tickers into lists, then explode
    df["tickers"] = df["tickers"].str.split(",")
    df = df.explode("tickers", ignore_index=True)

    # Clean individual ticker values
    df["tickers"] = df["tickers"].str.strip().str.upper()

    # Remove any rows where an individual ticker became empty after splitting
    df = df[df["tickers"].str.len() > 0].reset_index(drop=True)

    # Rename for clarity: each row now represents a single ticker
    df = df.rename(columns={"tickers": "ticker"})

    total_after_explode = len(df)
    logger.info(
        "After ticker explosion: %d rows (one per record-ticker pair).",
        total_after_explode,
    )

    # ------------------------------------------------------------------
    # Summary log (AC5)
    # ------------------------------------------------------------------
    logger.info(
        "Loader summary — Loaded: %d | Excluded: %d | Retained records: %d | "
        "Exploded rows: %d",
        total_loaded,
        excluded_count,
        retained_before_explode,
        total_after_explode,
    )

    # Attach fingerprint as DataFrame attribute for pipeline summary
    df.attrs["dataset_fingerprint"] = fingerprint

    return df
